language: csharp
mono: none
dotnet: 2.0.0
solution: FumeLab.Fume.sln
install:
  - nuget restore FumeLab.Fume.sln
  - nuget install NUnit.Runners -OutputDirectory testrunner
script:
 - dotnet restore
 - dotnet build
deploy:
skip_cleanup: true
provider: script
script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
on:
  branch: master
