language: csharp
mono: none
dotnet: 2.0.0
solution: FumeLab.Fume.sln
script:
 - dotnet restore
 - dotnet build
deploy:
skip_cleanup: true
provider: script
script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY $NUGET_SOURCE
on:
  branch: master
